レイアウト編集の修正
EC-CUBE/eccube-codeception pull request #139
Opened 2018-04-05 07:28 UTC by nanasess

以下の Pull Request に対応
https://github.com/EC-CUBE/ec-cube/pull/3017

2018-04-09 07:51 UTC, kiy0taka requested changes

2018-04-09 07:51 UTC, kiy0taka commented on tests/acceptance/EA06ContentsManagementCest.php
> +        $I->seeElement('div.ec-layoutRole__mainWithColumn');
`div.ec-layoutRole__main`のままでないとテストが失敗すると思います。

2018-04-09 08:19 UTC, nanasess commented on tests/acceptance/EA06ContentsManagementCest.php
> +        $I->seeElement('div.ec-layoutRole__mainWithColumn');
`div.ec-layoutRole__main` でも失敗するケースがあるようなので、 確実な `div.ec-layoutRole__footer` に変更しました

2018-04-10 00:28 UTC, kiy0taka approved these changes

2018-04-10 03:59 UTC, merged